spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://infrastructure-keycloak:80/auth/realms/car-rental/protocol/openid-connect/certs
          issuer-uri: http://infrastructure-keycloak:80/auth/realms/car-rental

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        max.block.ms: 5000
    properties:
      request.timeout.ms: 5000
    consumer:
      group-id: gateway-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8080
  address: 0.0.0.0

springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true

feign:
  okhttp:
    enabled: true
  httpclient:
    enabled: false

circuit-breaker:
  default-config:
    max-failure: 3
    min-success: 1
    timeout: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

keycloak:
  token-uri: ${KEYCLOAK_TOKEN_URI:http://infrastructure-keycloak:80/auth/realms/car-rental/protocol/openid-connect/token}
  client-id: ${KEYCLOAK_CLIENT_ID:rental-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:my-super-secret}
