version: "3"

services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - microservices-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - microservices-network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - microservices-network

  gateway-service:
    image: ${DOCKER_USERNAME:-local}/gateway-service:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - cars-service
      - rental-service
      - payment-service
      - logging-service
      - statistics-service
      - auth-service
    networks:
      - microservices-network

  cars-service:
    image: ${DOCKER_USERNAME:-local}/cars-service:${IMAGE_TAG:-latest}
    build: cars-service/
    ports:
      - "8070:8070"
    depends_on:
      - postgres
    networks:
      - microservices-network

  rental-service:
    image: ${DOCKER_USERNAME:-local}/rental-service:${IMAGE_TAG:-latest}
    build: rental-service/
    ports:
      - "8060:8060"
    depends_on:
      - postgres
    networks:
      - microservices-network

  payment-service:
    image: ${DOCKER_USERNAME:-local}/payment-service:${IMAGE_TAG:-latest}
    build: payment-service/
    ports:
      - "8050:8050"
    depends_on:
      - postgres
    networks:
      - microservices-network

  logging-service:
    image: ${DOCKER_USERNAME:-local}/logging-service:${IMAGE_TAG:-latest}
    build: logging-service/
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - microservices-network

  statistics-service:
    image: ${DOCKER_USERNAME:-local}/statistics-service:${IMAGE_TAG:-latest}
    build: statistics-service/
    ports:
      - "8100:8100"
    depends_on:
      - postgres
    networks:
      - microservices-network

  auth-service:
    image: ${DOCKER_USERNAME:-local}/auth-service:${IMAGE_TAG:-latest}
    build: auth-service/
    ports:
      - "8110:8110"
    depends_on:
      - postgres
    networks:
      - microservices-network

  frontend:
    image: ${DOCKER_USERNAME:-local}/frontend:${IMAGE_TAG:-latest}
    build: frontend/
    ports:
      - "80:80"
    depends_on:
      - gateway-service
    networks:
      - microservices-network

volumes:
  db-data:

networks:
  microservices-network:
    driver: bridge
