image:
  repository: "lilien0/logging-service"

service:
  port: 8090
  targetPort: 8090

resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "768Mi"
    cpu: "500m"

env:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/logging"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://infrastructure-keycloak:80/auth/realms/car-rental"
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: "http://infrastructure-keycloak:80/auth/realms/car-rental/protocol/openid-connect/certs"
