server:
  port: 8110
  address: 0.0.0.0
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/auth
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db-changelog_main.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://infrastructure-keycloak:80/auth/realms/car-rental}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://infrastructure-keycloak:80/auth/realms/car-rental/protocol/openid-connect/certs}
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      properties:
        max.block.ms: 5000
    properties:
      request.timeout.ms: 5000

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://infrastructure-keycloak:80/auth}
  realm: ${KEYCLOAK_REALM:car-rental}
  client-id: ${KEYCLOAK_CLIENT_ID:admin-cli}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:admin-secret}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
