apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.imageTag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            requests:
              {{- toYaml .Values.resources.requests | nindent 14 }}
              ephemeral-storage: "100Mi"
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
              ephemeral-storage: "256Mi"

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

          startupProbe:
            httpGet:
              path: {{ .Values.healthCheckPath }}
              port: http
            failureThreshold: 60
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheckPath }}
              port: http
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheckPath }}
              port: http
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
            timeoutSeconds: 5
      volumes:
        - name: tmp-volume
          emptyDir: {}
